{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('test', 'check')", "trace": "self = <test3.test_4.TestClass object at 0x00000222330374C0>\n\n    @allure.story(\"测试用例 2\")\n    def test_two(self):\n        x = \"test\"\n>       assert hasattr(x, 'check')\nE       AssertionError: assert False\nE        +  where False = hasattr('test', 'check')\n\ntest3\\test_4.py:13: AssertionError"}, "start": 1601360842206, "stop": 1601360842211, "uuid": "7daa152f-a8d7-4968-9251-c94c5a06fbb3", "historyId": "fb67a594575074fb76b471f308325fc3", "testCaseId": "1e18eeeb337bf33924402848d2a09f5f", "fullName": "test3.test_4.TestClass#test_two", "labels": [{"name": "story", "value": "测试用例 2"}, {"name": "feature", "value": "测试Dome"}, {"name": "parentSuite", "value": "test3"}, {"name": "suite", "value": "test_4"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "chenzhixiang"}, {"name": "thread", "value": "984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test3.test_4"}]}